version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: react-mui-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_APP_URL=${VITE_APP_URL}
      - VITE_APP_BASE_URL=${VITE_APP_BASE_URL}
      - VITE_APP_VERSION=${VITE_APP_VERSION}
      - VITE_APP_TITLE=${VITE_APP_TITLE}